config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get  '/login' ,    to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :edit, :update, :destroy]
  post '/guest', to: 'guest_sessions#create'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def edit
  end
  
  def new
  end
  
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "再設定用のURLを入力したメールに送信しました"
      redirect_to root_url
    else
      flash[:danger] = "お使いのメールアドレスは登録されていません"
      render 'new'
    end
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "パスワードの再設定が完了しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
    private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
        flash[:danger] = "無効なURLです。再度メールアドレスを入力してください"
        redirect_to new_password_reset_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "パスワード再設定URLの有効期限が過ぎています。再度メールアドレスを入力してください"
        redirect_to new_password_reset_url
      end
    end
end

app/views/password_resets/edit.html.erb
<% provide(:title, "パスワード再設定") %>
<div class="container form-container password_reset-container">
  <div class="row">
    <div class="col">
      <div class="form-logo-img">
        <%= link_to image_tag('Showin_logo.png', width: 100), root_path, class: "logo-img" %>
      </div>
      <h1 class="signup-title">パスワード再設定</h1>
      <%= form_with(model: @user, url: password_reset_path(params[:id]), local: true) do |form| %>
        <%= render 'shared/error_messages' %>

        <%= hidden_field_tag :email, @user.email %>
        <div class="form-group">
          <%= form.password_field :password, class: 'form-control', placeholder: "パスワード" %>
        </div>
        <div class="form-group">
          <%= form.password_field :password_confirmation, class: 'form-control', placeholder: "パスワード（再入力）" %>
        </div>
        <div class="form-group">
          <%= form.submit "送信", class: 'btn btn-info btn-lg form-submit' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "パスワード再設定依頼") %>
<div class="container form-container password_reset-container">
  <div class="row">
    <div class="col">
      <div class="form-logo-img">
        <%= link_to image_tag('Showin_logo.png', width: 100), root_path, class: "logo-img" %>
      </div>
      <h1 class="signup-title">パスワード再設定</h1>
      <%= form_with(scope: :password_reset, url: password_resets_path, local: true) do |form| %>
        <div class="form-group">
          <%= form.email_field :email, class: 'form-control', placeholder: "メールアドレス" %>
        </div>
        <div class="form-group">
          <%= form.submit "送信", class: 'btn btn-info btn-lg form-submit' %>
        </div>
      <% end %>
      <p class="form-go-to-signup-or-login">思い出した方は<%= link_to "こちら", login_path %></p>
    </div>
  </div>
</div>