config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get  '/login' ,    to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :edit, :update, :destroy]
  post '/guest', to: 'guest_sessions#create'
end

app/views/layouts/_figure.html.erb
<div class="container figure-container">
  <h1 class="title">グラフ</h1>
  <div class="figure-sum-and-button row">
    <span class="figure-sum-text col-sm">
      <div>合計：<em class="figure-sum"><%= sum_times %></em> 分</div>
      <div>（<em class="figure-sum"><%= to_hour %></em> 時間）</div>
    </span>
    <span class="dropdown col-sm">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= @user.microposts_period(@period).keys.first %> - <%= @user.microposts_period(@period).keys.last %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "週間", user_path(@user, period: "week"), class: "dropdown-item" %>
        <%= link_to "月間", user_path(@user, period: "month"), class: "dropdown-item" %>
        <%= link_to "年間", user_path(@user, period: "year"), class: "dropdown-item" %>
      </div>
    </span>
  </div>
  <div class="figure-container">
    <%= line_chart @chart %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-sm fixed-top navbar-expand">
      <a class="navbar-brand" href="#">
        <div class="navbar-brand-extend">
          <%= link_to image_tag('Showin_logo.png',width: 50),root_path, class: "logo-img" %>
          <%= link_to image_tag('Showin_text.png',height: 30),root_path, class: "logo-text" %>
        </div>
      </a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="menu" class="collapse navbar-collapse">
        <ul class="navbar-nav navbar-nav-extend ml-auto">
          <% if logged_in? %>
            <li class="nav-item nav-item-extend"><%= link_to "記録画面へ", user_path(current_user), class: "btn btn-info btn-md btn-extend" %></li>
            <li class="nav-item nav-item-extend"><%= link_to "プロフィール", edit_user_path(current_user), class: "btn btn-secondary btn-md btn-extend" %></li>
            <li class="nav-item nav-item-extend"><%= link_to "ログアウト", logout_path, method: :delete, class: "btn btn-danger btn-md btn-extend btn-logout-extend" %></li>
          <% else %>
            <li class="nav-item nav-item-extend"><%= link_to "新しく始める", signup_path, class: "btn btn-info btn-md btn-extend" %></li>
            <li class="nav-item nav-item-extend"><%= link_to "ログイン", login_path, class: "btn btn-info btn-md btn-extend btn-login-extend" %></li>
            <li class="nav-item nav-item-extend"><%= link_to "ゲストユーザー", guest_path,method: :post, class: "btn btn-info btn-login-extend navbar-extend-b navbar-extend-c" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_log.html.erb
<h1 class="log-title col-2">履歴</h1>
<% if @user.microposts.any? %>
  <div class="container">
    <ol class="microposts">
    <% @microposts.each do |micropost| %>
        <li id ="micropost-<%= micropost.id %>">
          <span class="row log-list">
            <span class="col-2 log-timestamp d-none d-md-inline-block log-timestamp-block">
              <span class="log-timestamp"><%= time_ago_in_words(micropost.created_at) %>前</span>
            </span>
            <span class="col-md-10 col-log-memos">
              <div class="log-time-and-edit">
                <div class="row">
                  <span class="log-time col-3">
                    <% if micropost.time.nil? %>
                      0分
                    <% else %>
                      <%= micropost.time %>分
                    <% end %>
                  </span>
                  <span class="col-7 log-timestamp log-timestamp-inline"><%= time_ago_in_words(micropost.created_at) %>前</span>
                  <span class="log-edit col-2"><%= link_to image_tag('memo.png', class: "log-edit-image"), edit_micropost_path(micropost) %></span>
                </div>
              </div>
              <span class="log-memo"><%= micropost.memo %></span>
              <% if micropost.picture.attached? %>
                <div class="log-picture">
            
                </div>
              <% end %>
            </span>
          </span>  
        </li>
    <% end %>
    </ol>
  </div>
  <%= paginate @microposts %>
<% else %>
  <span>まだ投稿がありません</span>
<% end %>

app/views/layouts/_micropost_form.html.erb
<div class="container micropost-container">
  <h1>記録</h1>
  <%= form_with(model: @micropost, url: microposts_path, local: true) do |form| %>
   
    <div class="form-group">
      <%= form.number_field :time, class: 'form-control', placeholder: "時間（分）を入力してください" %>
    </div>
    <div class="form-group">
      <%= form.text_area :memo, class: 'form-control', placeholder: "メモを加えてください" %>
    </div>
    <div class="form-group">
      <%= form.file_field :picture %>
    </div>
    <div class="form-group">
      <%= form.submit "記録する", class: 'btn btn-info btn-lg form-submit' %>
    </div>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= tag.div message, class: "alert alert-#{message_type}" %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
　</body>
  
</html>